# filepath: c:\Users\hp\Desktop\demoCICDnode\.github\workflows\ci.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies (including Jest)
      run: |
        npm ci
        npm install -g jest
        
    - name: Verify Jest installation
      run: |
        which jest
        jest --version

    - name: Run tests
      run: npm test
