# filepath: c:\Users\hp\Desktop\demoCICDnode\.github\workflows\ci.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20] # Updated to match your Node.js version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Update npm to the latest version
      run: npm install -g npm@latest

    - name: Verify npm version
      run: npm --version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test